### ISSUE TITLE
Feature: support handling line breaks instead of forcing to convert lines into an array first

### ISSUE THREAD

**Issue by JoernBerkefeld** [fib-at-isobar/beautyAmpCore#3]

**Comment by fib-at-isobar** [comment]
Will do when able.

**Comment by fib-at-isobar** [comment]
I've just finished this feature and it will be available in the next release.
You can now pass Array and String, and the output will match input data type.

**Comment by fib-at-isobar** [comment]
Released in `0.3.6`.
